customerRequest/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from .views import Modal, MoveCardView, createOnBoardRequest,CRM, CompanyProfile, RegisterView, HomeView


urlpatterns = [
    path('request/',login_required(createOnBoardRequest.as_view()), name='create-request'),
    path('crm/', login_required(CRM.as_view()), name='crm'),
    path('', HomeView.as_view(), name='home'),
    path('profile/', login_required(CompanyProfile.as_view()), name='profile'),
    path('move_card/', MoveCardView.as_view(), name='move_card'),
    path('register/', RegisterView.as_view(), name='users-register'),
    path('modal/', login_required(Modal.as_view()), name='modal'),
    path('logout/', auth_views.LogoutView.as_view(template_name='customerRequest/home.html'), name='logout'),
]

onboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from customerRequest.views import CustomLoginView, HomeView, DashboardView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/', include('customerRequest.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),
    path('', HomeView.as_view(), name='home'),
    path('dashboard/', login_required(DashboardView.as_view()), name='dashboard')
]

customerRequest/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import Group, Permission
from django.conf import settings
from django.db import models


class CustomerRequest(models.Model):
    service_type = models.CharField(max_length=255)
    number_of_users = models.IntegerField()
    about_platform = models.TextField()
    request_description = models.TextField()
    expected_date = models.DateTimeField()
    offer = models.PositiveIntegerField(blank=True, null=True)
    anything_else = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='request')
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=25, default='Initiation')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name  


class Company(models.Model):
    INDUSTRY_CHOICES = [
    ('IT', 'Information Technology'),
    ('finance', 'Finance'),
    ('healthcare', 'Healthcare'),
    ('business', 'Business')
    ]
    ETH = 'ETH'
    COUNTRY_CHOICES = [
        (ETH, 'Ethiopia')
    ]
    company_name = models.CharField(max_length=255)
    country = models.CharField(max_length=255, choices=COUNTRY_CHOICES)
    city = models.CharField(max_length=255)
    phone = models.IntegerField()
    tin_number = models.IntegerField()
    business_classification = models.CharField(max_length=255)
    industry = models.TextField(max_length=255, choices=INDUSTRY_CHOICES)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='company')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.company_name
    

class Schedule(models.Model):
    ACTIVITY_CHOICES = [
    ('meeting', 'Meeting'),
    ('call', 'Call'),
    ('email', 'Email'),
    ]
    activity_type = models.CharField(max_length=255, choices=ACTIVITY_CHOICES)
    due_date = models.DateTimeField()
    summary = models.TextField(null=True, blank=True)
    fee = models.TextField(max_length=255)
    request = models.OneToOneField(CustomerRequest, on_delete=models.CASCADE, related_name='schedule')

customerRequest/views.py
import json
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.views import View
from django.contrib import auth
from django.contrib import messages
from .form import LoginForm, RegisterForm, CustomerRequestForm, CompanyProfileForm
from .models import CustomerRequest, Company, Schedule
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from .email import send_email


class HomeView(View):
    def get(self, request):
        return render(request, 'customerRequest/home.html')


class DashboardView(View):
    def get(self, request):
        if request.user.is_staff:
            return render(request, 'customerRequest/admin_dashboard.html')
        return render(request, 'customerRequest/user_dashboard.html')

class createOnBoardRequest(View):
    form_class = CustomerRequestForm
    template_name = 'customerRequest/form.html'

    def get(self, request):
        form = self.form_class()
        try:
            Company.objects.get(user=request.user)
            return render(request, self.template_name, {'form': form})

        except Company.DoesNotExist:
            return redirect('profile')

    def post(self, request, *args, **kwargs):
        form = self.form_class()
        user = request.user
        description = request.POST.get('description')
        offer = request.POST.get('offer')
        service_type = request.POST.get('service_type')
        number_of_users = request.POST.get('users')
        about = request.POST.get('about_platform')
        expected_date = request.POST.get('expected_date')
        comments = request.POST.get('comments')
        new_request = CustomerRequest(user=user, service_type=service_type, number_of_users=number_of_users, offer=offer,
                                      about_platform=about, request_description=description, expected_date=expected_date, anything_else=comments)
        if new_request:
            new_request.save()
            messages.success(request, 'Request Sent.')
            return redirect('dashboard')


class CompanyProfile(View):
    form_class = CompanyProfileForm
    template_name = 'customerRequest/profile.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('create-request')
        return render(request, self.template_name)


class CRM(View):
    def get(self, request, *args, **kwargs):
        stages = [
            {'id': 1, 'name': 'Initiation', 'cards': CustomerRequest.objects.filter(
                status='Initiation').order_by('-created_at')},
            {'id': 2, 'name': 'Proposition',
                'cards': CustomerRequest.objects.filter(status='Proposition')},
            {'id': 3, 'name': 'Negotiation',
                'cards': CustomerRequest.objects.filter(status='Negotiation')},
            {'id': 4, 'name': 'Won',
                'cards': CustomerRequest.objects.filter(status='Won')},
            {'id': 5, 'name': 'Lost',
                'cards': CustomerRequest.objects.filter(status='Lost')},
        ]
        return render(request, 'customerRequest/crm.html', {'stages': stages})


@method_decorator(csrf_exempt, name='dispatch')
class MoveCardView(View):
    def post(self, request, *args, **kwargs):
        data = json.loads(request.body)
        cardId = data.get('cardId')
        to_id = data.get('toId')
        print(cardId, to_id)
        print(request.body)
        # Logic to move card in the backend (update CRM status)
        # For simplicity, we'll just update the status field in the model
        card = CustomerRequest.objects.get(id=cardId)
        card.status = to_id
        card.save()

        return HttpResponse('success')


class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'customerRequest/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='dashboard')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, 'customerRequest/register.html', {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, 'customerRequest/register.html', {'form': form})


class CustomLoginView(View):
    form_class = LoginForm
    template_name = 'customerRequest/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class()
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid Credentials.')
            return render(request, self.template_name, {'form': form})

class Modal(View):
    # form_class = ModalForm
    template_name = 'customerRequest/modal.html'

    def post(self, request, *args, **kwargs):
        request_id = request.POST.get('request')
        try:
            request_instance = CustomerRequest.objects.get(id=request_id)
            activity_type = request.POST.get('activity_type')
            due_date = request.POST.get('due_date')
            summary = request.POST.get('summary')
            fee = request.POST.get('fee')
            new_schedule = Schedule(activity_type=activity_type, due_date=due_date,
                                    summary=summary, fee=fee, request=request_instance)
            if new_schedule:
                new_schedule.save()
                send_email(request_instance.user.email,
                           request_instance.user.first_name, due_date, activity_type)
                return redirect('crm')
        except CustomerRequest.DoesNotExist:
            print("Doesn't exist")

customerRequest/templates/customerRequest/admin_dashboard.html
{% extends 'index.html' %}

{% block content %}
<div class=" container mt-5 vh-100 d-flex align-items-center justify-content-center">
    <h1>Admin Dashboard</h1>
</div>

{% endblock content %}

customerRequest/templates/customerRequest/crm.html
{% extends 'index.html' %} {% load static %} {% block content%}
 

  <!-- <div class="container "> -->
    <div class="container my-3"> 
      <div class="row justify-content-start">
        <!-- To do tasks -->
        {% for stage in stages %}
        <div
          class="col shadow-sm rounded-3 mx-1 my-3 border border-dark border-1 bg-silver py-2"
          id="{{ stage.name }}"
          ondrop="drop(event)"
          ondragover="allowDrop(event)"
        >
          <h5  class="row justify-content-center">{{ stage.name }}</h5>
          {% for card in stage.cards%}
          <div>
            <div
              id='{{card.id}}'
              ondragstart="dragStart(event,'{{card.id}}')"
              draggable="true"
              class="card rounded-3 w-100 mb-3 shadow-sm">
              <div class="card-body px-3 py-3">
                <h5 class="card-title">{{card.service_type}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">
                  {{card.user.company}}
                </h6>
                <p class="card-text">{{card.user.company.city}}</p><p class="card-text"><b>{{card.offer}}ETB</b></p>
                <p class="card-text">{{card.expected_date.date|date:'M. d, Y' }}</p>
                <button
                type="button"
                class="btn btn-outline-success btn-sm"
                data-toggle="modal"
                data-target="#exampleModal"
                data-whatever="@mdo"
                  >
                  Schedule
                </button>
                {% with request=card.id %}
                {% include 'customerRequest/modal.html'%}
                {% endwith %}
                <!-- {%if card.status == 'Initiation'%} -->
                <!-- {% endif %} -->
    
                <input type="hidden" value="{{card.id}}" />
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endfor %}
      </div>
  </div> 

  <script>
   function dragStart(event,val) {
    event.dataTransfer.setData("Text", event.target.id);
    event.dataTransfer.setData("val", val);

}
function allowDrop(event) {
    event.preventDefault();
}
function drop(event) {
    if (event.target.id != "") {
        event.preventDefault();
        const data = event.dataTransfer.getData("Text");
        const val = event.dataTransfer.getData("val");

        event.target.appendChild(document.getElementById(data));
        console.log(val,event.target.id)
        user = {
            "cardId":  val,
            "toId":  event.target.id
        }

        // Options to be given as parameter 
        // in fetch for making requests
        // other then GET
        let options = {
            method: 'POST',
            headers: {
                'Content-Type':
                    'application/json;charset=utf-8'
            },
            body: JSON.stringify(user)
        }

        // Fake api for making post requests
        let fetchRes = fetch(
            "http://127.0.0.1:8000/customer/move_card/",
            options);
        fetchRes.then(res =>
            res.json()).then(data => {
                console.log("data###", data)
            })

        // // initial list
        // if (event.target.id == "todo") {
        //     document.getElementById(data).classList.remove("border-warning", "border-success");
        //     document.getElementById(data).classList.add("border-primary"); 
        // }
        // // progress list
        // if (event.target.id == "progress") {
        //     document.getElementById(data).classList.remove("border-primary", "border-success");
        //     document.getElementById(data).classList.add("border-warning"); 
        // }
        // // completed list
        // if (event.target.id == "completed") {
        //     document.getElementById(data).classList.remove("border-warning", "border-success");
        //     document.getElementById(data).classList.add("border-success"); 
        // }
    }
}
  </script>
  <style>
    body {
      background: #dce8dc;
    }

    .fill {
      position: relative;
      height: 150px;
      width: 150px;
      top: 5px;
      left: 5px;
      cursor: pointer;
    }

    .empty {
      display: inline-block;
      height: 100px;
      width: 100px;
      margin: 10px;
      /* background-color: #ccc; */
    }

    .hold {
      border: 4px solid lightgray;
    }

    .hovered {
      background: #ddd;
      /*border-style: dashed;*/
    }

    .invisible {
      display: none;
    }
  </style>
  <!-- <div class="qualification">
    <h4>Qualification</h4>
    {% for request in requests %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{request.service_type}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{request.about_platform}}</h6>
          <p class="card-text">{{request.request_description}}</p>
          <a href="#" class="card-link">Check</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
      {% endfor%}
  </div>
  <div class="proposition">
    <h4>Proposition</h4>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
  </div>
  <div class="negotiation">
    <h4>Negotiation</h4>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div>
      </div>
  </div>
  <div class="won">Won</div>
  <div class="lost">Lost</div> -->
</div>
{% endblock %} {% block styles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{% endblock %}

customerRequest/templates/customerRequest/form.html
{% extends 'index.html'%} 
{% load bootstrap5 %}
{% bootstrap_css %}
{% block content %}
<div class="container w-50 my-3 shadow-lg rounded-3">
<form action="" method="POST" class="row g-3 mx-3 my-3">
    {% csrf_token %}
      <div class="col-md-6">
        <label for="service-type" class="form-label">Service Type<span class="text-danger">*</span></label>
          <select class="form-select" aria-label="Select an item" name="service_type">
          <option  value="swift">SWIFT Connect</option>
        </select>
      </div>
      <div class="col-md-6">
        <label for="users" class="form-label">Number of Users<span class="text-danger">*</span></label>
        <input type="number" name="users" class="form-control" id="users" required>
      </div>
      <div class="col-md-6">
        <label for="users" class="form-label">Offer</label>
        <input type="number" name="offer" placeholder="offer in ETB" class="form-control" id="users" required>
      </div>
      <div class="col-md-6 mb-3"> 
        <label for="id_expected_date">Expected Date<span class="text-danger">*</span></label>
        <input type="date" name="expected_date" placeholder="yyyy-mm-dd" class="form-control" required="" id="id_expected_date">
    </div>
      <div class="col-12">
        <label for="inputAddress" class="form-label">Tell us about your Platform<span class="text-danger">*</span></label>
        <textarea class="form-control" name="about_platform" id="about_platform" rows="3" required></textarea>
      </div>
      <div class="col-12">
        <label for="inputAddress" class="form-label">Request Description<span class="text-danger">*</span></label>
        <textarea class="form-control" name="description" id="description" rows="3" required></textarea>
      </div>
      <div class="col-12">
        <label for="comments" class="form-label">Anything else(optional)</label>
        <textarea class="form-control" name="comments" id="comments" rows="3"></textarea>
      </div>
      <div class="d-flex col-12 justify-content-center align-items-center my-3">
        <button type="submit" class="btn btn-primary">Submit Request</button>
      </div>
      </div>
</form>
{% endblock %}
</div>

{% block datepicker%}
    <!-- Add these links to the head section of your HTML file -->
    <link
      rel="stylesheet"
      href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"
    />
    <script src="https://code.jquery.com/jquery-3.6.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Optionally, you can add a theme for the datepicker -->
    <link
      rel="stylesheet"
      href="https://code.jquery.com/ui/1.12.1/themes/base/theme.css"
    />

{% endblock %}

<script>
  // Add this JavaScript block to initialize the date picker
  $(function () {
      // Target the input with the "datepicker" class
      $(".datepicker").datepicker({
          dateFormat: "yyyy-mm-dd",  // Adjust the date format as needed
          changeMonth: true,
          changeYear: true,
          yearRange: "-100:+0",  // Allow selection of the last 100 years
      });
  });
</script>


{{form.as_p}}

customerRequest/templates/customerRequest/home.html
{% extends 'index.html' %}


{% block content %}
<div class=" container mt-5 vh-100 d-flex flex-column align-items-center justify-content-center">
    <h1>welcome!</h1>
    <div class="d-flex">

        <a href="{% url 'login' %}" class="btn btn-primary m-3">Log in</a>
        <a href="{% url 'users-register' %}" class="btn btn-primary m-3">Sign up</a>
    </div>
</div>
{% endblock %}

customerRequest/templates/customerRequest/login.html
{% extends "index.html" %}
{% block title %} Login Page {% endblock title%}
{% block content %}
<div class="form-content my-3 p-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
          <div class="card-header justify-content-center">
            <h3 class="font-weight-light my-1 text-center">Sign In</h3>
          </div>
          {% if form.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
              {% for key, value in form.errors.items %}
              <strong>{{ value }}</strong>
              {% endfor %}
            </div>
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          <div class="card-body">
            <form action="" method="POST">
              {% csrf_token %}
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1">Username</label>
                    {{ form.username }}
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1">Password</label>
                    {{ form.password }}
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <!-- Add a Remember me functionality -->
                    {{ form.remember_me }}
                    <label> Remember me</label>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group mt-0 mb-1">
                    <button
                      name="login"
                      class="col-md-12 btn btn-dark"
                      id="login"
                    >
                      Sign in
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="card-footer text-center">
            <div class="small">
              <a href="{% url 'users-register' %}"
                >Don't have an account yet? Go to signup</a
              ><br />
              <a href="#"><i>Forgot Password?</i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

customerRequest/templates/customerRequest/logout.html
{% extends "index.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Thanks for your time, contact me for any comments or suggestions using my email address.
        </p>
        <br><hr><a href="{% url 'login' %}" class="btn btn-primary">Sign in again</a>
        </div>
    </div>


{% endblock content %}

customerRequest/templates/customerRequest/modal.html
{% block content %}
<div
  class="modal fade"
  id="exampleModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Schedule</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="http://127.0.0.1:8000/customer/modal/" method="POST">
          {% csrf_token%}
          <div class="col form-group">
            <label for="activity-type" class="form-label"
              >Activity Type<span class="text-danger">*</span></label
            >
            <select class="form-select" aria-label="Select an item" name="activity_type">
              <option>--------</option>
              <option value="meeting">Meeting</option>
              <option value="call">Call</option>
              <option value="email">Email</option>
            </select>
          </div>
          <div class="col form-group">
            <label for="id_due_date"
              >Due Date <span class="text-danger"></span
            ></label>
            <input
              type="date"
              name="due_date"
              placeholder="yyyy-mm-dd"
              class="form-control"
              required
              id="id_due_date"
            />
          </div>
          <div class="col form-group">
            <label for="fee" class="form-label"
              >Fee<span class="text-danger">*</span></label
            >
            <input
              type="text"
              name="fee"
              class="form-control"
              id="fee"
              required
            />
          </div>
          <div class="col form-group">
            <label for="summary" class="form-label">Summary</label>
            <textarea
              class="form-control"
              name="summary"
              id="summary"
              rows="3"
            ></textarea>
          </div>
          <input
              type="hidden"
              name="request"
              value="{{request}}"
              class="form-control"
              id="fee"
              required
            />
            <button
              type="button"
              class="btn btn-secondary"
              data-dismiss="modal"
            >
              Close
            </button>
            <button type="submit" class="btn btn-success">Save</button>
        </form>
      </div>
      {% endblock %}
    </div>
  </div>
</div>

customerRequest/templates/customerRequest/profile.html
{% extends 'index.html' %}

{% block content %}
<form action="" method="POST">
    {% csrf_token%}
    <div class='card mt-5' style='width: 30rem;  padding: 10px; margin-right: auto; margin-left: auto'>
        {{form.as_p}}
        <input type="submit" value="Register" class="btn btn-primary"> 
    </div>
</form>
{% endblock %}

customerRequest/templates/customerRequest/register.html
{% extends 'index.html'%}
 
{% if form.errors %}
<div class="alert alert-danger alert-dismissible" role="alert">
  <div id="form_errors">
    {% for key, value in form.errors.items %}
    <strong>{{ value }}</strong>
    {% endfor %}
  </div>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %} 
{% block title %} Register Page {% endblock title%} 
{% block content %}
<div class="form-content my-3 p-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-7">
        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
          <div class="card-header justify-content-center">
            <h3 class="font-weight-light my-4 text-center">Create Account</h3>
          </div>
          <div class="card-body">
            <form method="POST">
              {% csrf_token %} {% if form.errors %}
              <div class="alert alert-danger alert-dismissible" role="alert">
                <div id="form_errors">
                  {% for key, value in form.errors.items %}
                  <strong>{{ value }}</strong>
                  {% endfor %}
                </div>
                <button
                  type="button"
                  class="close"
                  data-dismiss="alert"
                  aria-label="Close"
                >
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endif %}
              <div class="form-row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="small mb-1">First Name</label>
                    {{ form.first_name }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="small mb-1">Last Name</label>
                    {{ form.last_name }}
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="small mb-1">Username</label>
                    {{ form.username }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="small mb-1">Email</label>
                    {{ form.email }}
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="small mb-1">Password</label>
                    {{ form.password1 }} {{ form.errors.password }}
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="small mb-1">Confirm Password</label>
                    {{ form.password2 }}
                  </div>
                </div>
              </div>
              <div class="form-group mt-4 mb-0">
                <button type="submit" class="col-md-12 btn btn-dark">
                  Sign Up</button
                ><br /><br />
              </div>
            </form>
          </div>
          <div class="card-footer text-center">
            <div class="small">
              <a href="{% url 'login'%}">Have an account? Go to Sign in</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

customerRequest/templates/customerRequest/user_dashboard.html
{% extends 'index.html' %}

{% block content %}
<div class="container mt-5 vh-100 d-flex align-items-center justify-content-center">
    <h1>User Dashboard</h1>
</div>

{% endblock content %}